[dependencies]
axum = "0.6"
color-eyre = "0.6.5"
tokio = {version = "1", features = ["full"]}

[dev-dependencies]
httpc-test = "0.1.1"

[package]
edition = "2021"
name = "axum-webapp"
version = "0.1.0"
